import XCTest

@testable import AdventOfCode

final class Day11Tests: XCTestCase {
  // Smoke test data provided in the challenge question
  let testData = """
    ...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....
    """

  let cosmicExpansion = """
    ....#........
    .........#...
    #............
    .............
    .............
    ........#....
    .#...........
    ............#
    .............
    .............
    .........#...
    #....#.......
    """

  func test_part1() {
    let challenge = Day11(data: testData)
    XCTAssertEqual(String(describing: challenge.part1()), "374")
  }

  func test_expand() {
    let challenge = Day11(data: testData)
    var grid = challenge.grid
    challenge.expand(grid: &grid)
    print(grid.prettyPrinted)
    XCTAssertEqual(grid.prettyPrinted, cosmicExpansion)
  }

  func test_part2() {
    let challenge = Day11(data: testData)
    XCTAssertEqual(String(describing: challenge.part2()), "Todo")
  }
}
