import XCTest

@testable import AdventOfCode

final class Day11Tests: XCTestCase {
  // Smoke test data provided in the challenge question
  let testData = """
    ...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....
    """

  let cosmicExpansion = """
    ....#........
    .........#...
    #............
    .............
    .............
    ........#....
    .#...........
    ............#
    .............
    .............
    .........#...
    #....#.......
    """

  func test_part1() {
    let challenge = Day11(data: testData)
    XCTAssertEqual(String(describing: challenge.part1()), "374")
  }

  func test_part2() {
    let challenge = Day11(data: testData)
    XCTAssertEqual(String(describing: challenge.part2()), "82000210")
  }

  func test_shortedPathSum() {
    let challenge = Day11(data: testData)
    XCTAssertEqual(challenge.shortestPathSum(expansionFactor: 10), 1030)
    XCTAssertEqual(challenge.shortestPathSum(expansionFactor: 100), 8410)
  }
}
